[build]
  command = "npm run build -- --configuration production"
  publish = "dist/secure-vault-military"
  
[context.production]
  environment = { NODE_VERSION = "18" }

[context.deploy-preview]
  command = "npm run build"

# Simple SPA config (no plugins needed)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
