[build]
  command = "npm run build:prod"
  publish = "dist/secure-vault-military"
  
[context.production]
  environment = { NODE_VERSION = "18" }

[context.deploy-preview]
  command = "npm run build"

[[plugins]]
  package = "@netlify/plugin-angular-universal"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
