# Simple SPA configuration with correct output directory
[build]
  command = "npm run build -- --configuration production"
  publish = "dist/securevault-military"

[context.production]
  environment = { NODE_VERSION = "18" }

[context.deploy-preview]
  command = "npm run build"

# For Single Page Applications
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
