[build]
  command = "npm run build -- --configuration production"
  publish = "dist/secure-vault-military"
  
[context.production]
  environment = { NODE_VERSION = "18" }

[context.deploy-preview]
  command = "npm run build"

# Option 1: Disable all plugins (recommended for client-side Angular apps)
[plugins]
  package = []

# Option 2: If you really need Angular Universal (server-side rendering)
# Uncomment these lines and comment out the [plugins] section above
# [[plugins]]
#   package = "@netlify/plugin-angular-universal"
#   [plugins.inputs]
#     projectName = "secure-vault-military"

# For Single Page Applications
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
