[build]
  command = "npm run build:prod"
  publish = "dist/secure-vault-military"
  
[context.production]
  environment = { NODE_VERSION = "18" }

[context.deploy-preview]
  command = "npm run build"

# No plugins needed for standard Angular app

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
